### PR TITLE
feat: calendar api support

### PR DESCRIPTION
**Pull request by tarrencev**

### CODE REVIEW

**Comment by jrdnull** [comment]
Thanks @tarrencev, the tests are currently failing. I had a look at this locally and got them passing, but I can't push to this PR so I've attached the diff.

Changes:
- Fix Unmarshal (need to strip quotes)
- Fix test case mismatch
- Add offset/limit to Calendars()
- Update README to show new support
- Make linter happy

If you update your branch with the changes we can merge this in, thanks for contributing :+1: 

[diff.txt](https://github.com/Teamwork/nylas-go/files/6905987/diff.txt)

**Review by jrdnull — CHANGES_REQUESTED** [review]
See previous comment

**Comment by tarrencev** [comment]
Hi @jrdnull thanks for your feedback. I'll take some time today to incorporate your changes.

**Comment by tarrencev** [comment]
@jrdnull I've added the changes. thanks for the feedback! I'm going to work on adding events support now

**Pull request merged**
