### PR TITLE
Added tracking to draft request

### PR DESCRIPTION
**Pull request by movitz-s**
Hi!

I added a simple struct to represent the tracking field in drafts as described [here](https://docs.nylas.com/docs/message-tracking).

Thanks for making this library!

### CODE REVIEW

**Comment by jrdnull** [comment]
Brilliant, thank you 👍

**Comment by mog33m** [comment]
pod 'Instabug'

**Review by mog33m — COMMENTED** [review]
pod 'Instabug'

**Comment by mog33m** [comment]
🥺

**Pull request merged**
